Repository camel-tooling/camel-dap-client-vscode, pull requests merged in 2023-08, with the labels that each got.

#453 FUSETOOLS2-2154: Add Set Exchange property test
  .github/workflows/insider.yaml
  .github/workflows/main.yaml
  src/ui-test/resources/demo route.camel.yaml
  src/ui-test/tests/camel.settings.test.ts
  src/ui-test/tests/command.palette.test.ts
  src/ui-test/tests/context.menu.test.ts
  src/ui-test/tests/debugger.test.ts
  src/ui-test/tests/editor.actions.test.ts
  src/ui-test/tests/reload.test.ts
  src/ui-test/utils.ts
Labels: READY FOR REVIEW, PRIO

#461 Configure eslint to warn about floating promises
  .eslintrc.json
Labels: READY FOR REVIEW

#462 Fix floating promises warings
  src/extension.ts
  src/test/runTest.ts
  src/test/suite/completion.task.test.ts
  src/ui-test/uitest_runner.ts
Labels: READY FOR REVIEW

#465 Bump vscode-uitests-tooling from 4.0.3 to 4.0.5
  package-lock.json
  package.json
  src/ui-test/tests/debugger.test.ts
  src/ui-test/utils.ts
Labels: READY FOR REVIEW, PRIO

#470 Fix Command Quotation issue
  src/task/CamelJBangTaskProvider.ts
  src/test/suite/camel.jbang.version.settings.test.ts
  src/test/suite/camel.version.settings.test.ts
  src/test/suite/util.ts
Labels: bug, READY FOR REVIEW

#421 FUSETOOLS2-1743 Add JBang lense debug test
  package-lock.json
  package.json
  src/ui-test/tests/01_install.test.ts
  src/ui-test/tests/codelens.test.ts
  src/ui-test/uitest_runner.ts
  src/ui-test/utils.ts
  src/ui-test/variables.ts
Labels: READY FOR REVIEW

#422 FUSETOOLS2-2051: Provide Red Hat Maven repository with Jbang by default when version contains redhat
  CHANGELOG.md
  package.json
  src/task/CamelJBangTaskProvider.ts
  src/test/suite/maven.repository.settings.test.ts
  src/ui-test/tests/camel.settings.test.ts
  src/ui-test/utils.ts
Labels: READY FOR REVIEW

#478 FUSETOOLS2-2151 Add JBang lense run test
  src/ui-test/tests/codelens.test.ts
Labels: READY FOR REVIEW
